name: ejak_driweather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  get: 4.6.6
  http: ^1.3.0
  location: ^8.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass-Regular.ttf
        - asset: assets/fonts/Overpass-Italic.ttf
          style: italic
        - asset: assets/fonts/Overpass-Thin.ttf
          weight: 100
        - asset: assets/fonts/Overpass-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Overpass-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Overpass-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Overpass-Light.ttf
          weight: 300
        - asset: assets/fonts/Overpass-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Overpass-Medium.ttf
          weight: 500
        - asset: assets/fonts/Overpass-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Overpass-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Overpass-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Overpass-Bold.ttf
          weight: 700
        - asset: assets/fonts/Overpass-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Overpass-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Overpass-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Overpass-Black.ttf
          weight: 900
        - asset: assets/fonts/Overpass-BlackItalic.ttf
          weight: 900
          style: italic
