part of "app_theme.dart";

TextTheme textTheme = TextTheme(
  displayLarge: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 56.0.sp,
    fontWeight: FontWeight.w900,
    letterSpacing: 0,
    height: 0,
  ),
  displayMedium: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 48.0.sp,
    fontWeight: FontWeight.w900,
    letterSpacing: 0,
    height: 0,
  ),
  displaySmall: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 36.0.sp,
    fontWeight: FontWeight.w900,
    letterSpacing: 0,
    height: 0,
  ),
  headlineLarge: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 40.0.sp,
    fontWeight: FontWeight.w800,
    letterSpacing: -4.5.w,
    height: 1.14.h,
    color: Color(0xFF494A4B),
  ),
  headlineMedium: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 32.0.sp,
    fontWeight: FontWeight.w700,
    letterSpacing: 0,
    height: 0,
  ),
  headlineSmall: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 24.0.sp,
    fontWeight: FontWeight.w700,
    letterSpacing: 0,
    height: 0,
  ),
  titleLarge: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 18.0.sp,
    fontWeight: FontWeight.w700,
    letterSpacing: 0,
    height: 0,
  ),
  titleMedium: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 16.0.sp,
    fontWeight: FontWeight.w700,
    letterSpacing: 0,
    height: 0,
  ),
  titleSmall: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 14.0.sp,
    fontWeight: FontWeight.w700,
    letterSpacing: 0,
    height: 0,
  ),
  bodyLarge: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 18.0.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    color: Color(0xFF494A4B),
    height: 0,
  ),
  bodyMedium: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 16.0.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    height: 0,
  ),
  bodySmall: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 14.0.sp,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    height: 0,
  ),
  labelLarge: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 16.0.sp,
    fontWeight: FontWeight.w300,
    letterSpacing: 0,
    height: 0,
  ),
  labelMedium: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 14.0.sp,
    fontWeight: FontWeight.w300,
    letterSpacing: 0,
    height: 0,
  ),
  labelSmall: TextStyle(
    fontFamily: 'Overpass',
    fontSize: 12.0.sp,
    fontWeight: FontWeight.w200,
    letterSpacing: 0,
    height: 0,
  ),
);
